name: openpatent

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  openpatent:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /openpatent') ||
      startsWith(github.event.comment.body, '/openpatent')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run openpatent
        uses: sst/openpatent/github@latest
        env:
          openpatent_API_KEY: ${{ secrets.openpatent_API_KEY }}
          openpatent_PERMISSION: '{"bash": "deny"}'
        with:
          model: openpatent/claude-opus-4-5
